[package]
name = "il2cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
anyhow = "1.0"
object = "0.31.1"
byteorder = "1.4.3"

